spring.application.name=API_Server
# server.port=8080
server.port=2010

# Datasource
# spring.datasource.jdbc-url=jdbc:sqlserver://192.168.1.11:2000;databaseName=WarehouseDB;trustServerCertificate=true;useUnicode=true;characterEncoding=UTF-8;
spring.datasource.jdbc-url=jdbc:sqlserver://192.168.1.54:2012;databaseName=WarehouseDB;trustServerCertificate=true;useUnicode=true;characterEncoding=UTF-8;
spring.datasource.username=sa
spring.datasource.password=Sql201293@
# spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ------------------- Database thứ hai (NB2024_App - Fast Internal) -------------------
spring.datasource.fast.jdbc-url=jdbc:sqlserver://192.168.1.100:1433;databaseName=NB2024_App;trustServerCertificate=true;useUnicode=true;characterEncoding=UTF-8
spring.datasource.fast.username=sa
spring.datasource.fast.password=Sql2014
spring.datasource.fast.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.default_schema=dbo
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.use_nationalized_character_data=false

# Giới hạn kích thước file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Cấu hình nén file tĩnh
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
server.compression.min-response-size=1024

server.max-http-request-header-size=64KB
# logging.level.org.apache.coyote.http11=DEBUG

# Telegram Bot Configuration
telegram.bot-token=8750206729:AAFN3S_gviKwDbbiUpYfKjfahlI-j91-GOA
telegram.chat-id=5639159074

file.root-path=D:\

spring.datasource.sendStringParametersAsUnicode=false
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.jpa.properties.hibernate.format_sql=true
